<a href="https://colab.research.google.com/github/sanjaysanjel/FirstRepo/blob/master/2nd_Week_Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [0]:
from keras.models import Sequential
from keras.utils.np_utils import to_categorical
from keras.layers import Dense

In [9]:
from google.colab import files
uploaded = files.upload()

Saving Admission_Predict.csv to Admission_Predict (1).csv


In [0]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['Admission_Predict.csv']))

In [17]:
df2

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit 
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
2             3        316          104  ...  8.00         1              0.72
3             4        322          110  ...  8.67         1              0.80
4             5        314          103  ...  8.21         0              0.65
5             6        330          115  ...  9.34         1              0.90
6             7        321          109  ...  8.20         1              0.75
7             8        308          101  ...  7.90         0              0.68
8             9        302          102  ...  8.00         0              0.50
9            10        323          108  ...  8.60         0              0.45
10           11        325          106  ...  8.40         1              0.52
11           12        327          111  ...  9.00         1              0.84
12           13        328          112  ...  9.10         1              0.78
13           14        307          109  ...  8.00         1              0.62
14           15        311          104  ...  8.20         1              0.61
15           16        314          105  ...  8.30         0              0.54
16           17        317          107  ...  8.70         0              0.66
17           18        319          106  ...  8.00         1              0.65
18           19        318          110  ...  8.80         0              0.63
19           20        303          102  ...  8.50         0              0.62
20           21        312          107  ...  7.90         1              0.64
21           22        325          114  ...  8.40         0              0.70
22           23        328          116  ...  9.50         1              0.94
23           24        334          119  ...  9.70         1              0.95
24           25        336          119  ...  9.80         1              0.97
25           26        340          120  ...  9.60         1              0.94
26           27        322          109  ...  8.80         0              0.76
27           28        298           98  ...  7.50         1              0.44
28           29        295           93  ...  7.20         0              0.46
29           30        310           99  ...  7.30         0              0.54
..          ...        ...          ...  ...   ...       ...               ...
370         371        310          103  ...  8.24         0              0.72
371         372        324          110  ...  9.22         1              0.89
372         373        336          119  ...  9.62         1              0.95
373         374        321          109  ...  8.54         1              0.79
374         375        315          105  ...  7.65         0              0.39
375         376        304          101  ...  7.66         0              0.38
376         377        297           96  ...  7.43         0              0.34
377         378        290          100  ...  7.56         0              0.47
378         379        303           98  ...  7.65         0              0.56
379         380        311           99  ...  8.43         1              0.71
380         381        322          104  ...  8.84         1              0.78
381         382        319          105  ...  8.67         1              0.73
382         383        324          110  ...  9.15         1              0.82
383         384        300          100  ...  8.26         0              0.62
384         385        340          113  ...  9.74         1              0.96
385         386        335          117  ...  9.82         1              0.96
386         387        302          101  ...  7.96         0              0.46
387         388        307          105  ...  8.10         0              0.53
388         389        296           97  ...  7.80     

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
y = df2["Chance of Admit "]

In [0]:
not_needed = ["Serial No.","Chance of Admit "]
X =  df2.drop(not_needed, axis=1)

In [0]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [29]:
X.shape


(400, 7)

In [31]:
model = Sequential()
model.add(Dense(units=10,input_dim=7,activation="relu"))
model.add(Dense(units=10,activation="relu"))
model.add(Dense(units=5,activation="relu"))
model.add(Dense(units=5,activation="relu"))

model.add(Dense(units=1,activation="sigmoid"))
model.compile(loss="mae",optimizer="sgd")
model.summary()

W0809 08:44:51.685658 139714031884160 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 10)                80        
_________________________________________________________________
dense_7 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_8 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_9 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 6         
Total params: 281
Trainable params: 281
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(X,y,epochs=150, validation_split=0.1)

W0809 08:51:24.541119 139714031884160 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0809 08:51:24.581297 139714031884160 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Train on 360 samples, validate on 40 samples
Epoch 1/150
360/360 [==============================] - 1s 2ms/step - loss: 0.3608 - val_loss: 0.3720
Epoch 2/150
360/360 [==============================] - 0s 65us/step - loss: 0.3315 - val_loss: 0.3437
Epoch 3/150
360/360 [==============================] - 0s 55us/step - loss: 0.3045 - val_loss: 0.3191
Epoch 4/150
360/360 [==============================] - 0s 51us/step - loss: 0.2812 - val_loss: 0.2970
Epoch 5/150
360/360 [==============================] - 0s 52us/step - loss: 0.2608 - val_loss: 0.2767
Epoch 6/150
360/360 [==============================] - 0s 52us/step - loss: 0.2428 - val_loss: 0.2598
Epoch 7/150
360/360 [==============================] - 0s 51us/step - loss: 0.2285 - val_loss: 0.2464
Epoch 8/150
360/360 [==============================] - 0s 65us/step - loss: 0.2171 - val_loss: 0.2358
Epoch 9/150
360/360 [==============================] - 0s 60us/step - loss: 0.2072 - val_loss: 0.2278
Epoch 10/150
360/360 [================

In [35]:
df2.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [0]:
user_input = [
    [320, 115,4,4,4,6.5,1],
    [315,115,4,4,3,7,0]
]

In [0]:
user_input = scaler.transform(user_input)

In [62]:
user_input.round(3)

array([[320. , 115. ,   4. ,   4. ,   4. ,   6.5,   1. ],
       [315. , 115. ,   4. ,   4. ,   3. ,   7. ,   0. ]])

In [63]:
model.predict(user_input)

array([[1.],
       [1.]], dtype=float32)

In [0]:
one_input = np.array([100,100,2,2,2,2.1,1]).reshape(1,-1)

In [0]:
one_input = scaler.transform(one_input)

In [77]:
model.predict(one_input)

array([[0.9999994]], dtype=float32)